config/routes.rb
RailsPerftest::Application.routes.draw do
  resources :device_types

  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :device_type
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
  has_many :devices, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/device_types_controller.rb
class DeviceTypesController < InheritedResources::Base

  def create
    @device_type = DeviceType.new(device_type_params)
    @device.save!
  end

private

  def device_type_params
    params.require(:device).permit(:name)
  end
end

app/controllers/devices_controller.rb
class DevicesController < InheritedResources::Base

  def show
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(device_params)
    @device.save!
  end

private

  def device_params
    params.require(:device).permit(:name, :device_type_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/device_types/_form.html.erb
<%= form_for(@device_type) do |f| %>
  <% if @device_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_type.errors.count, "error") %> prohibited this device_type from being saved:</h2>

      <ul>
      <% @device_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_types/edit.html.erb
<h1>Editing device_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @device_type %> |
<%= link_to 'Back', device_types_path %>

app/views/device_types/index.html.erb
<h1>Listing device_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @device_types.each do |device_type| %>
      <tr>
        <td><%= device_type.name %></td>
        <td><%= link_to 'Show', device_type %></td>
        <td><%= link_to 'Edit', edit_device_type_path(device_type) %></td>
        <td><%= link_to 'Destroy', device_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device type', new_device_type_path %>

app/views/device_types/new.html.erb
<h1>New device_type</h1>

<%= render 'form' %>

<%= link_to 'Back', device_types_path %>

app/views/device_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device_type.name %>
</p>

<%= link_to 'Edit', edit_device_type_path(@device_type) %> |
<%= link_to 'Back', device_types_path %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :device_type %><br>
    <%= f.number_field :device_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Device type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.device_type %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Device type:</strong>
  <%= @device.device_type_id %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPerftest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>